name: CI S3-apps caller workflow

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  #push:
    #branches:
    #  - main

  #pull_request:
  #  branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  call-reusable-workflow:
    name: Graasp app sticky notes
    uses: graasp/graasp-deploy/.github/workflows/cintegration-s3-apps.yml@33c1d6065fba3b8761b7425d386ca3c4d7af8ceb
    with:
      build-folder: 'build'
      version: 'latest'
    secrets:
      aws-access-key-id: ${{ secrets.APPS_AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.APPS_AWS_SECRET_ACCESS_KEY }}
      aws-region: ${{ secrets.APPS_AWS_REGION }}
      aws-s3-bucket-name: ${{ secrets.APPS_DEV_BUCKET }}
      app-id: ${{ secrets.APP_ID }}
      graasp-domain-dev: ${{ secrets.DEV_GRAASP_DOMAIN }}
      cloudfront-distribution: ${{ secrets.APPS_DEV_CLOUDFRONT_DISTRIBUTION }}

